### ISSUE TITLE
Tracking issue for pattern formatters

### ISSUE THREAD

**Issue by Lancern** [SpriteOvO/spdlog-rs#10]
This issue tracks the development progress of **pattern formatters**. The development takes place under branch `pattern-formatter`.

- [x] Basic pattern combinators
- [x] `pattern!`
- [x] Atom patterns (reference: [spdlog patterns](https://github.com/gabime/spdlog/wiki/3.-Custom-formatting))
  - [x] Literal string
  - [x] Payload (`{v}`, `{payload}`)
  - [x] Thread ID (`{t}`, `{tid}`)
  - [x] Process ID (`{p}`, `{pid}`)
  - [x] Logger name (`{n}`, `{logger}`)
  - [x] Log level (`{l}`, `{level}`)
  - [x] Short log level (`{L}`, `{level-short}`)
  - [x] Abbreviated weekday name (`{a}`, `{weekday-name}`)
  - [x]  Full weekday name (`{A}`, `{weekday-name-full}`)
  - [x]  Abbreviated month name (`{b}`, `{month-name}`)
  - [x]  Full month name (`{B}`, `{month-name-full}`)
  - [x]  Full date time (`{c}`, `{datetime}`)
  - [x]  2-digit year (`{C}`, `{year-short}`)
  - [x]  4-digit year (`{Y}`, `{year}`)
  - [x]  Short date (`{D}`, `{date-short}`)
  - [x]  Month 01-12 (`{m}`, `{month}`)
  - [x]  Day of month 01-31 (`{d}`, `{day}`)
  - [x]  Hours in 24 format 00-23 (`{H}`, `{hour}`)
  - [x]  Hours in 12 format 01-12 (`{I}`, `{hour-12}`)
  - [x]  Minutes 00-59 (`{M}`, `{minute}`)
  - [x]  Seconds 00-59 (`{S}`, `{second}`)
  - [x]  Millisecond part of the current second 000-999 (`{e}`, `{millisecond}`)
  - [x]  Microsecond part of the current second 000000-999999 (`{f}`, `{microsecond}`)
  - [x]  Nanosecond part of the current second 000000000-999999999 (`{F}`, `{nanosecond}`)
  - [x]  AM / PM (`{p}`, `{ampm}`)
  - [x]  12 hour clock (`{r}`, `{time-12}`)
  - [x]  24 hour HH:MM time (`{R}`, `{time-short}`)
  - [x]  ISO 8601 time format (HH:MM:SS) (`{T}`, `{X}`, `{time}`)
  - [x]  ISO 8601 offset from UTC in timezone ([+/-] HH:MM) (`{z}`, `{tz-offset}`)
  - [x]  Seconds since epoch (`{E}`, `{unix}`)
  - [x] Full formatter (`{+}`, `{full}`)
  - [x]  Color range (`{^...$}`)
  - [x]  Source file, line and column (`{@}`, `{loc}`)
  - [x]  Basename of source file (`{s}`, `{source-basename}`)
  - [x]  Full or relative path of the source file (`{g}`, `{source}`)
  - [x]  Source line (`{#}`, `{line}`)
  - [x]  Source column (`{%}`, `{column}`)

**Comment by Lancern** [comment]
The development status of the pattern formatters are now tracked in PR #12.
